# conf/config.yaml
# 默认为True, 控制台打印消息
debug: true

# 日志保留天数
log_days: 3

# 指定进程数
process_num: 4

# 宠汪汪进程数
joy_process_num: 1

# 宠汪汪喂食狗粮克数
joy_feed_count: 20

# 拼图签到进程数
jd_puzzle_process_num: 1

# 京东COOKIES
jd_cookies:
  - pt_pin=;pt_key=;

# 东东农场是否使用水滴换豆卡, 100水滴换20京豆
jd_farm_bean_card: false

# 东东农场每天保留多少水滴, 用于明天的十次浇水任务
jd_farm_retain_water: 80

# 消息通知
notify:
  # TG机器人Token
  tg_bot_token: null
  # TG用户ID
  tg_user_id: null
  # TG代理
  tg_bot_api: null
  # push+ token: https://pushplus.hxtrip.com/
  push_plus_token: null

  # push+ group 一对多推送才需要次配置
  push_plus_group: null

  # 依次填上corpid的值,corpsecret的值,touser的值,agentid,media_id的值，注意用,号隔开。
  qywx_am: null

  #  server酱通知key
  server_send_key: null
# 在此列表中的脚本, 将不会加入到定时任务中, 如需立即生效, 请手动执行命令: docker-entrypoint
crontab_exclude_scripts:
  - jd_bean_indiana.py


# 京东试用商品分类, 英文逗号分隔, 可选列表: 全部商品,家用电器,手机数码,电脑办公,家居家装,美妆护肤,服饰鞋包,母婴玩具,生鲜美食,图书音像,钟表奢品,个人护理,家庭清洁,食品饮料.更多惊喜
jd_try_cid_list: 家用电器, 手机数码, 电脑办公, 家居家装

# 京东试用类型, 英文逗号分隔, 可选列表: 全部试用,普通试用,闪电试用,30天试用
jd_try_type_list: 普通试用,闪电试用

# 京东试用商品最低价格
jd_try_min_price: 100

# 京东试用商品提供商品最大数量, 商品提供量多的是辣鸡商品
jd_try_goods_count: 10

# 京东试用商品过滤关键词, 用@分隔
jd_try_filter_keywords: 玉@教程@软件@英语@辅导@培训@表带@皮带@瑜伽垫@水饺@燕窝@高钙奶@纯牛奶@树苗@集体课@现场课@奶粉@看房游@口服液@灸贴@云南旅游@掌之友@金满缘@新兴港隆@拆机@品鉴@试饮@咨询@零基础@直播课@体验@网课@训练营@礼品袋@装修@快狐@疣@包皮@疏通@药@鱼胶@狗狗@幼犬@戒烟@尿垫@浪潮英信@专家@长高课@饲料@代办@美缝剂@体验@遮瑕@洗面奶@洁面乳@抗皱@膏@猫砂@购房@消食@积食@软胶囊@养生茶@驼背@房产@辅食@打印纸@财务管理@进销存@实战@生发液@早泄@阳痿@染发@补血@珍珠粉@玛咖@灰指甲@阿胶@维生素@同仁堂@讲堂@教材@补肾@精品课@开发@疹@疮@疥@软膏@真题@模拟题@专车接送@看海@看房@学员@投资@通关@名师@节课@酵素@滴眼液@全国流量@奶粉@香皂@精油@爱犬@课程@教学@教程@猫人@学车@你拍一@手机壳@益生菌@宠物@会计@考试@职称@漱口水@吊坠@胶原蛋白@鲜花@蛋白粉@降血糖@降血脂@降血压@管理系统@收银系统@体检@检查@减肥@玫瑰花@股票@丰胸@避孕套@保湿@补水@粉底@口红@耳钉@耳环@耳坠@收纳盒@大王卡@管理软件@博仑帅@荧光笔@原子笔@月租@上网卡@不限流量@日租卡@洗车机@热水袋@钥匙扣@饼干@甲醛检测@贴膜@美容器@拖鞋@桨叶@烫发@清洁套装@鼠标垫@数据线@硒鼓@壁纸@防晒霜@护手霜@面霜@添加剂@修复@祛疤@精华液@玻尿酸@挂画@壁画@精华水@润滑油@机油@普洱茶@吸奶器@吸顶灯@爽肤水@面膜@冰箱底座@胶漆@小靓美@洁面扑@内衣@胸罩@文胸@卷尺@种子@档案袋@塑料袋@垃圾袋@癣@脚气@阴道@生殖器@肛门@狐臭@老太太@妇女@私处@孕妇@卫生巾@卫生条@培训@洋娃娃@男孩玩具@女孩玩具@益智@女性内衣@女性内裤@女内裤@女内衣@女孩@三角裤@鱼饵@钓鱼@尿杯@安全座椅@玩具@娃娃@网课@课程@辅导@网校@电商@车载充电器@网络课程@美少女@纸尿裤@英语@俄语@四级@六级@四六级@在线网络@在线@阴道炎@宫颈@糜烂@喷剂@飞机杯@手机膜@钢化膜@水凝膜@手机壳@手机支架@钢化膜@猫粮@狗粮@戒指@手链@项链@手镯@牙刷@加湿器@水垢@喷雾@茶叶@净水壶@眼霜@香水@墨盒@墨水@墨粉@颜料@中性笔@钢笔@马克笔@震动棒@自慰器@延时@触媒


# chromium路径, 默认不需要修改，除非你是本地运行或者进行开发。
chrome_path: /usr/bin/chromium
